
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: kimoDb
      MYSQL_ROOT_PASSWORD: tima04
      MYSQL_PASSWORD: tima04
      MYSQL_USER: root
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-app}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      PMA_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      - database
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
